# Generated by Django 5.0.3 on 2024-04-29 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('FullName', models.CharField(max_length=250)),
                ('CustomerID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Resident', models.CharField(max_length=250)),
                ('PhoneNumber', models.CharField(max_length=250)),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('DateOfBirth', models.DateTimeField()),
                ('PassportSize', models.ImageField(upload_to='Passports/')),
                ('CarID', models.ImageField(upload_to='Documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentName', models.CharField(max_length=250)),
                ('HeadOfDepartment', models.CharField(max_length=250)),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('DepartmentId', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('FullName', models.CharField(max_length=250)),
                ('EmployeeID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.department')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarID', models.CharField(max_length=250)),
                ('CarStatus', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=50, null=True)),
                ('PaymentAmount', models.FloatField()),
                ('RegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved')], default='Pending', max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.car')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='services',
            field=models.ManyToManyField(through='sasrws.ServiceRecord', to='sasrws.service'),
        ),
    ]
