# Generated by Django 5.0.3 on 2024-04-30 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasrws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_serviced_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_serviced_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='next_service_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DistanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sasrws.car')),
            ],
        ),
    ]
